### ISSUE TITLE
Wrong relay status

### ISSUE THREAD

**Issue by dsbrar** [Paulraita/homebridge-relays#1]
Home application shows wrong status of the relay. when relay is on its shows off when we restart the home application on iphone or iwatch.

**Comment by smartechru** [comment]
Hello
I updated some parts. PIN output was inverted.
Please check again and let me know the result.
Thanks.

**Comment by dsbrar** [comment]
now when we on the relay its gets off and when we off the relay its gets on. its inverted.

**Comment by smartechru** [comment]
I updated again. Please recheck again.
![image](https://user-images.githubusercontent.com/32426840/38184800-5b2a21d8-3674-11e8-8a6f-03578057098c.png)

If it's not working correctly, please modify the parts I highlighted.
And please let me know the result.
Thanks.

**Comment by dsbrar** [comment]
it same as in my first comment.

**Comment by smartechru** [comment]
Please explain in detail.
I have no RPi now, so I can't test in my side.

**Comment by dsbrar** [comment]
when we on the relay it gets on and after restarting home app the status of relay in home application is off but relay is on.

**Comment by smartechru** [comment]
Did you only restart Home App without restarting Homebridge?
If you only restart Home App, this can be happened.

**Comment by dsbrar** [comment]
only coming out from app and again going to app also cause this.

**Comment by smartechru** [comment]
Let me clarify about this issue.
1. If you restart homebridge, I think in Home App, all relay accessories and mechanical relays are off.
2. If you click relay accessory in Home App, the relay status is changed.
3. In this status, if you restart your Home App, mechanical relay is off but in Home App relay accessory shows on.

I think this is the issue what you faced. Right?

**Comment by dsbrar** [comment]
yes

**Comment by Paulraita** [comment]
In my side, it's difficult to fix without Raspberry Pi.
We can solve this issue using Teamviewer.

**Comment by ChockymilK** [comment]
Were you ever able to rectify this?
iOS Home app Relay status matches the relay state. On = On, Off = Off
If you close the Home app, and re-open, set states are inverted. App= On, Relay = Off

**Comment by Botas1989** [comment]
Pls upload  npm package, there is only version 0.0.1

**Comment by gilesdavison** [comment]
To elaborate on what I think @dsbrar was trying to say, the only thing that is round the wrong way is the HomeKit view of the devices.

To reproduce what I'm talking about: when starting Homebridge and opening HomeKit all of the devices are shown as on in HomeKit but the relay shows every device as off, when you initially click on a device to turn it off nothing changes on the relay as they're already off but the HomeKit icon changes to off. When clicking it again the relay then switches on and the HomeKit icon switches on. 

It seems HomeKit's view of the devices needs to be swapped, I tried my luck with the invert option and default_state added by @revarbat, but it didn't seem to change anything. Except make the devices get very out of sync and behave oddly in general.

**Comment by smartechru** [comment]
I've just updated the plugin and published it to `npmjs` store. https://www.npmjs.com/package/homebridge-relays
