### ISSUE TITLE
My relay times out

### ISSUE THREAD

**Issue by robiotik** [Paulraita/homebridge-relays#5]
Hello, I can't control my relay, this comes in the console :(

[2020-5-12 17:41:13] [Relay-1] Relay status for 'Relay-1', pin 3 is true
[2020-5-12 17:41:14] [Relay-1] Relay for 'Relay-1', pin 3 timed out.

**Comment by Alsharifi** [comment]
That message is not an indication of why you cannot control your relay, that is supposed to be displayed when "duration_ms" expires. confirm that you are addressing the physical pin and not GIPO address. 

duration_ms | If given, accessory will stay ON for this many milliseconds, then turn OFF. Timer resets if accessory is turned ON again while it is still ON.(Default: 0/None)
