### ISSUE TITLE
I would like to ask if i could have the source code before build 

### ISSUE THREAD

**Issue by dylanbarne** [Paulraita/homebridge-relays#8]
May I have the source code to build a custom relay switch for my garage that make use of a ultrasonic distance sensor to check whether the garage is open. 

If yes you can contact me dylan14022005@gmail.com

**Comment by smartechru** [comment]
Hi @dylanbarne,

Well... I didn't get your point. If you can explain more detail about what you are going to do, that would be brilliant.
Please feel free to ask me if you have any questions.

**Comment by dylanbarne** [comment]
I want to build a component which uses and ultrasonic distance sensor to detect whether my garage is open and then uses that to set the garage to either the on or off position. I am unsure of how to use typescript for homebridge in combination with gpio. The documentation seems to be missing some important stuff. 😆 Thanks for any help you can give

**Comment by toshibochan** [comment]
For garage door I use https://www.npmjs.com/package/homebridge-gpio-garagedoor-d

**Comment by smartechru** [comment]
Here is a typescript version of the garage door plugin - https://github.com/KraigM/homebridge-gpio-garagedoor
Feel free to message me if you have any questions.

**Comment by dylanbarne** [comment]
Thank you so much, how does he turn on the gpio pin using typescript. In his code there is no specific point where he tells the raspberry to turn the pin on, this is the closest he gets 
![image](https://user-images.githubusercontent.com/49467498/111437558-28b64000-8753-11eb-80b5-3cb8b5b5ea4e.png)
